### ISSUE TITLE
prevent decimal pixel coordinates

### ISSUE THREAD

**Issue by annthurium** [twilio-labs/open-pixel-art#1188]
People started adding decimal pixel coordinates, and we don't want that because it messes up the grid.

community member @dpeukert wrote a unit test to prevent this in https://github.com/twilio-labs/open-pixel-art/pull/1141 (thanks!) but we should also move the existing decimal pixel coordinates to the next available pixel.

**Comment by dkundel** [comment]
Resolved by #1223 and #1141
