### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Samibanley** [twilio-labs/open-pixel-art#1317]
The CONTRIBUTING.md says there will be pixels marked as `"<UNCLAIMED>"`, however, there are not. There was another issue and a PR to fix this, but the PR was closed due to it's potential in breaking validation. 

The next best solution would be to simply remove those instructions from the documentation and replace them with clearer instructions.

**Comment by Samibanley** [comment]
I would like to tackle this myself for Hacktoberfest, if that is okay.

**Comment by Xabadu** [comment]
Fixed in #1318
