### ISSUE TITLE
Specifaction of Matrix with 39 x 39

### ISSUE THREAD

**Issue by Prathamesh404** [twilio-labs/open-pixel-art#1325]
- I got following error, which indicates the pixel value should be be between 0 to 39
- I attached the Screenshot of the error i received
![Screenshot 2019-10-20 at 11 09 10 PM](https://user-images.githubusercontent.com/25879588/67163656-1e8de780-f38f-11e9-9b98-d0e9e9005c88.png)

**Comment by deadpyxel** [comment]
Sorry, but which pixel did you try to claim?

**Comment by Prathamesh404** [comment]
```json
   {"y": 38,
      "x": 39,
      "color": "#10c9de",
      "username": "artdevgame"
    },
    {
      "y": 39,
      "x": 0,
      "color": "#623CE4",
      "username": "toddmoy"
    },
......
  {
      "y": 39,
      "x": 39,
      "color": "#0f111a",
      "username": "PrateekPunetha"
    }
  ]
```
- The above stated are some of the values in the _data.json .As we see the value of y resets after every 39 values of x.
- Does the matrix is allowed to contain 39 rows and 39 columns?
- Any insight around this can be helpful.

**Comment by deadpyxel** [comment]
I'll try to simulate this error on a local environment. But I think it is allowed to have (39, 39) as a pixel.

**Comment by Prathamesh404** [comment]
Yeah but what about adding 40, 0. Is (39,39) is the last co-ordinate for
the pixels? That's what I was asking for.

**Comment by Xabadu** [comment]
Hey @Prathamesh404! Yes, that is correct. 39, 39 is the last available coordinate. The whole grid is 40x40 (starting from 0).

Closing this for now, but please let us know if you have any more questions!

**Comment by Prathamesh404** [comment]
Was looking forward to add some swag from Twilio. Never MInd, thanks.
