### ISSUE TITLE
Improving menu

### ISSUE THREAD

**Issue by iiCe89** [twilio-labs/open-pixel-art#149]
@dkundel Is it possible to change **_site/index.html** i was trying to update menu so its within container  so it aligned with rest of page . but doesn't seem to allow me to?

**Comment by dkundel** [comment]
Hey @iiCe89 absolutely! Where was it failing? It's expected that Danger fails. It will just cause a manual code review instead.

**Comment by iiCe89** [comment]
yeh i Editted file and ran NPM test and it would revert file back to original state ?

**Comment by iiCe89** [comment]
seems _site is within the .gitignore file as page doesn't seem to exist until i've ran NPM start

**Comment by dkundel** [comment]
Oh yeah my bad. You need to edit `index.njk` if you want to modify `_site/index.html`. and then run `npm run build` or `npm start` to generate it. You should only check in `index.njk`
