### ISSUE TITLE
Trying to add a new pixel, but auto test failing

### ISSUE THREAD

**Issue by spianoDev** [twilio-labs/open-pixel-art#1651]
Hello! 

I tried to add my pixel to the project, but the auto test failed with a message that said I deleted another user's information. However, I was very careful to add a single line and insert my information into an empty spot. I noticed that there are many similar errors inside the current active pull requests. Please let me know how I can help resolve this issue.

Thanks!
spianoDev

**Comment by SoftCreatR** [comment]
Had the same problem, because the file changes too often. Easiest workaround is:

```
cd open-pixel-art
npm run sync-fork
git push --set-upstream origin add-my-new-pixel
```

**Comment by spianoDev** [comment]
That seems to have worked. Thank you so much!

**Comment by BrianLoveGa** [comment]
Thanks... I keep trying to merge the new additions . But the merge conflicts never appear in my VS code not sure how to resolve them. Just gonna delete and re clone the whole thing to start over... again...
