### ISSUE TITLE
Address Duplicates

### ISSUE THREAD

**Issue by simeydk** [twilio-labs/open-pixel-art#206]
Right now there is nothing in place to prevent pixels "overwriting" each other.

If this is deliberate then please close this issue.

Ideas to address this:
- Order the existing list (by x,y)
- Add a test to enforce that the list should be ordered by x and y
- Add a test to enforce that there are no duplicates in the list

**Comment by ConorGrocock** [comment]
I'll take this one

**Comment by simeydk** [comment]
LOL. I opened this issue with the intention on working on it myself, but to be fair I did not actually claim it. Interested to see your implementation @ConorGrocock  :)

**Comment by simeydk** [comment]
Something that also needs to be addressed is that there are existing duplicates. How are you treating those?

**Comment by ConorGrocock** [comment]
I've forgotten to claim issues far to many times in the past week. So I get it.

I wasn't sure how to deal with it. So I made a seperate commit where I changed the position to one that is similar to the existing one. It's not a great solution but it's the only one that I could think of.

**Comment by dkundel** [comment]
@simeydk or @ConorGrocock who of you two is working on the unit test for verifying duplicates? Now that we have the sorted file this should be easier to enforce but the test would still be useful for the automatic merging.

**Comment by simeydk** [comment]
I'd like to give it a go. Will submit something soon

**Comment by dkundel** [comment]
Thanks for contributing @simeydk :) can we add the test that checks for order as well? I think @ConorGrocock had one ready already.

**Comment by ConorGrocock** [comment]
I'll submit a new pull request with my order test

**Comment by dkundel** [comment]
Thank you both of you for your contributions!
