### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kt-aakash** [twilio-labs/open-pixel-art#2135]
## Description
 **npm run sort : oprn-pixels** not working..!

## Expected Behavior
As mentioned in the objective of TwilioQuest's help section, this function is supposed to sort the values in the **._data/pixels.json** file

## Actual Behavior
Gives the following error messages :
npm ERR! missing script: sort:open-pixels
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     format:sort-pixels

## Possible Fix
Not familiar with this.

## Steps to Reproduce
After creating a repo on the local machine and adding the new json attribute to **._data/pixels.json** file, try running the command :   **npm run sort : oprn-pixels**

## Context
I had to take care of the sorting manually by myself.

**Comment by tesla809** [comment]
Yea found the same issue:
check the package.json file.

Run `npm run format:sort-pixels` instead.

**Comment by charlietankers** [comment]
I added a PR for this: https://github.com/twilio-labs/open-pixel-art/pull/2180

**Comment by dkundel** [comment]
Thanks for the fix!
