### ISSUE TITLE
Improve "That pixel was contributed by:" empty state

### ISSUE THREAD

**Issue by M0nica** [twilio-labs/open-pixel-art#215]
When a pixel isn't contributed by someone it says "That pixel was contributed by:" without a username.

Could the text be ommitted or updated to say "contribute to this pixel" or  something that effect and link to https://open-pixel-art.com/#contributing

<img width="844" alt="Screen Shot 2019-10-03 at 7 19 32 AM" src="https://user-images.githubusercontent.com/6998954/66122617-2f2c1880-e5ae-11e9-91e9-fd14022c2be4.png">

I'd be interested in implementing either solution if different functionality is desired.

**Comment by athif23** [comment]
Can we just completely remove them, and change them as a tooltip (#226) instead? I mean, in my case it's kinda hard to see the contributor name if you hover the top part of the canvas. Like, you need to scroll down again, which the contributor name maybe change, as the cursor move too, or zoom out the page to completely show all of them, but that's not an option in my opinion. Also, maybe we can keep them, but also add the tooltip to make it easier for some user.

**Comment by M0nica** [comment]
On mobile I was only able to see who contributed what pixel in that box so I think it would be good to retain it.

**Comment by athif23** [comment]
I see, I didn't know that. I think would just do them both.

**Comment by dkundel** [comment]
Yeah the idea behind the box was to make it at least a bit mobile friendly :) so I think having both is a good idea!

**Comment by dkundel** [comment]
Implemented in #284. Thank you @athif23 and @M0nica!
