### ISSUE TITLE
Colorize: That pixel was contributed by

### ISSUE THREAD

**Issue by M0nica** [twilio-labs/open-pixel-art#217]
When hovering over pixels and seeing `"That pixel was contributed by: ${user}"` the text is always red. Can the text be updated to match the color of the pixel?  There could be visual accessibility concerns with this approach. It could be set up to colorize the username to match the contribution only if the contrast passes a certain threshold using an approach like: https://24ways.org/2010/calculating-color-contrast/

**Comment by dkundel** [comment]
Implemented in #284. Thank you @athif23 and @M0nica!
