### ISSUE TITLE
Improve hovering over pixels

### ISSUE THREAD

**Issue by athif23** [twilio-labs/open-pixel-art#226]
My screen is not so big, so when I try to hover on the top side of canvas, I can't see who contribute to it, as I need to scroll down to see them, but it would change the name by then. Or, I can see them, but I need to zoom out my browser to do that, and there's no way I would do such thing. So, what if instead of put it below the canvas, we make them as a tooltip, that would always follow mouse position.

I'm interesting on implementing this one, in fact I'm currently try doing it.

**Comment by dkundel** [comment]
This is a cool idea. Could you please coordinate with @M0nica since she raised #217 and #215. I'm not opposed to have both a tool-tip and the current implementation with the improvements outlined by @M0nica :)

**Comment by athif23** [comment]
Okay :)

**Comment by dkundel** [comment]
Implemented in #284. Thank you @athif23!
