### ISSUE TITLE
[BUG] Postinstall script hangs on Windows 10 after configuring merge driver

### ISSUE THREAD

**Issue by rmkubik** [twilio-labs/open-pixel-art#2423]
## Description

User in Windows 10 on node 12.18.2 had the postinstall hook hang on `Configured custom merge driver` for over an hour.

Had them remove the postinstall hook, and everything worked fine. Had them check their git config and the configurations made by postinstall hook were in place.

I'm wondering if there is some inappropriately handled exit case on Windows?

[Original report in TwilioQuest Slack](https://twilioquest.slack.com/archives/CJDL29HJB/p1596836251162500).

## Expected Behavior

Postinstall script should update git config and then terminate the node installation.

## Actual Behavior

Postinstall script seems to hang after configuring git

## Steps to Reproduce

1.
2.
3.
4.

## Context

Prevented TQ player from progressing in Hacktoberfest mission.

**Comment by jefs42** [comment]
I'm having this issue right this moment, glad I found this thread. I will follow steps in original Description to get around the issue.

`PS C:\Users\jefs4\Documents\TWILIO\projects\open-pixel-art> npm install

> open-pixel-art@1.0.0 postinstall C:\Users\jefs4\Documents\TWILIO\projects\open-pixel-art
> npm run configure:merge-driver


> open-pixel-art@1.0.0 configure:merge-driver C:\Users\jefs4\Documents\TWILIO\projects\open-pixel-art
> node scripts/configureMergeDriver.js

√ Configured custom merge driver`

And it's stuck there.

**Comment by Gatodillo** [comment]
Hello! Updating npm from 6.12 to 6.14.8 makes no change. I have updated the version of the package ora from "^4.0.2" to "^5.1.0" and now I can access to pixel art on localhost. How can I test if this doesn't break something?

**Comment by Gatodillo** [comment]
@jesuslerma Do you have an opinion about this change? This happened after I see you in a zoom meeting (CCOSS) and tried to install open pixel art  :) Thank you!

**Comment by jesuslerma** [comment]
Hi @Gatodillo please discard the changa You put ok package.json close #2423 and then send another PR only with the changes on _data/pixels.json file

**Comment by Gatodillo** [comment]
I have not touched pixels.json :( , just package.json and the package lock file.

**Comment by jesuslerma** [comment]
I see. Sorry I missed your point. If you're looking to contribute fixing this issue, then your PR Is ok, You just need to wait for a Review from maintainers. If you want to contribute by adding pixels You just need to update the pixels.json with your pixel.

**Comment by Gatodillo** [comment]
OK @jesuslerma, thank you!
