### ISSUE TITLE
[BUG] Uppercase vs lowercase username

### ISSUE THREAD

**Issue by spiracular** [twilio-labs/open-pixel-art#2537]
Small one, but the TwilioQuest check doesn't detect completion if you use an Uppercase username. It always parses the inputted username as all-lowercase, and then subsequent checks will fail. True for pixel-alteration and pull request challenges.

(Worked fine after I switched to the using same github username in lowercase. Maybe that's for the best, anyway.)

**Comment by RvQ** [comment]
I seem to have been with the same issue
`We found the Pull Request #2963 on the Open Pixel Art remote repository, but it doesn't belong to your GitHub user "rvq"!
`

**Comment by Armslice** [comment]
Yes! I'm not crazy. Me too. Is this a bug in open-pixel-art, or is it in Twilio-quest?

**Comment by rvq** [comment]
> Yes! I'm not crazy. Me too. Is this a bug in open-pixel-art, or is it in Twilio-quest?

Twilio-Quest. If you enter the username in Twilioquest it converts it to lowercase. The initial tests pass. There Twilio test cases dont seem to mind the case sensitivity mismatch. But on that final pull request it is case sensitive. Luckyly we have a workaround with changing the username in github - [LINK](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/changing-your-github-username)

**Comment by armslice** [comment]
This is still a bug. The work around is to change the your github username
to all lowercase but there is still an issue with TQ not allowing uppercase
usernames.

**Comment by jacrys** [comment]
still occurring, and changing username didn't fix it

**Comment by jsatuaho** [comment]
> 
> 
> still occurring, and changing username didn't fix it

Did you go to the first task and change the username there as well? Changing there and on github did the trick for me.

**Comment by jacrys** [comment]
> > still occurring, and changing username didn't fix it
> 
> Did you go to the first task and change the username there as well? Changing there and on github did the trick for me.

I finally got it to work.  btw, you can change it from settings, you don't have to go back to the tasks.  There is a section in settings where all of your env information is stored.
