### ISSUE TITLE
npm run test doesn't work if you don't have prettier installed globally

### ISSUE THREAD

**Issue by simeydk** [twilio-labs/open-pixel-art#331]
The tests use prettier, but this doesn't work if you don't have it installed globally. Here's a screenshot:

![image](https://user-images.githubusercontent.com/13088589/66229660-a1057e80-e6e2-11e9-9402-4f77d5568aad.png)

**Comment by simeydk** [comment]
I would like to give this a go, but might need some guidance :).

**Comment by simeydk** [comment]
... I just realised this is my mistake, because I didn't run `npm install` again after pulling from master after prettier was added.

This is a bit of a gotcha though. Is doing a `npm install` after a `git pull` something I should generally get in the habit of doing, or is there a way to set things up to get a notification or something if you pulled a change that requires `npm install` to be rerun?

**Comment by apennell** [comment]
I think if you pay attention to the files that are updated/added when you pull, you can take an update to `package.json` as a likely sign that you need to run `npm install`.

**Comment by simeydk** [comment]
Thanks! Last question: what's the best/easiest way to determine what changed after running `git pull`?

**Comment by dkundel** [comment]
it typically prints you a summary of the files that changed. But you can also always just run `npm prune && npm install` and it will remove anything you might have installed that's not in the `package.json` and install whatever is missing.
