### ISSUE TITLE
Add instructions on keeping fork up to date with upstream repo

### ISSUE THREAD

**Issue by GK-Hynes** [twilio-labs/open-pixel-art#340]
The contributing docs are really excellent and beginner-friendly. 

One issue that contributors might run into during Hacktoberfest is that new commits by other contributors could make their fork go out of sync with the upstream repository before they have finished their own pull request.

Adding a link to [GitHub's instructions on syncing a fork](https://help.github.com/en/articles/syncing-a-fork), or a paragraph with similar instructions, could be useful.

**Comment by thatrobotdev** [comment]
I'll take this one! #436

**Comment by dkundel** [comment]
Thanks for the contribution!
