### ISSUE TITLE
Add changed pixels to expected commit message

### ISSUE THREAD

**Issue by apennell** [twilio-labs/open-pixel-art#362]
### The Issue
During times of high commit volume like Hacktoberfest, or when the stars align against you, someone else may be working on updating the same pixel as you are. With a generic recommended commit message, you need to dig into every open PR to view the file changes in order to check what pixels were changed in the open PRs that are ahead of yours.

### Proposed solution
The [contributing guidelines](https://github.com/twilio-labs/open-pixel-art/blob/master/CONTRIBUTING.md#branching-and-committing) give specific instructions to add your commit with the message `feat(pixels): add my new pixel.`, following the [Conventional Commits Standard](https://www.conventionalcommits.org/en/v1.0.0-beta.4/). By adding your claimed pixel to the commit message (and, therefore, your automatic PR title), one can easily do a visual scan of the PRs waiting to be merged to make sure they aren't about to try to change a pixel that will soon be merged and cause a conflict. For example, `feat(pixels): add my new pixel (8, 27).` This solution would be loosely implemented by updating that section of the docs.

Somewhat related to #340

**Comment by apennell** [comment]
Assuming this is a change that is desired, I'd like to take this issue on.

**Comment by dkundel** [comment]
Thank you for raising this and contributing!! :)
