### ISSUE TITLE
`.screenreader-only` element cover up the canvas

### ISSUE THREAD

**Issue by athif23** [twilio-labs/open-pixel-art#374]
When you try to hover the top left pixel, some pixel doesn't show up the tooltip. I try to search where the problem is, and found out that `.screenreader-only` element cover up some of the pixels. This can solve easily by adding `z-index: -1;` to `.screenreader-only` styles, but is it fine to do that? It wouldn't changes the accessibility, right?

#### Without `z-index: -1;`
![n7XgH6lqrh](https://user-images.githubusercontent.com/15215827/66249360-968bc900-e764-11e9-9046-e00a1e672d85.gif)

#### With `z-index: -1;`
![WTlJYA6kef](https://user-images.githubusercontent.com/15215827/66249361-97245f80-e764-11e9-81f7-a21a32fe4ff9.gif)

**Comment by gemanepa** [comment]
@athif23[ I made the last accessibility PR modifying .screenreader-only between other things](https://github.com/twilio-labs/open-pixel-art/pull/345/files)
You are probably referring to this element being the culprit...
`<div role="heading" aria-level="2" class="screenreader-only">Pixel Art Canvas</div>`
...Right?

Adding `z-index: -1;` shouldn't affect the accessibility, do it! Once your PR gets merged just in case I will check the app with a SR, and if something somewhere stopped being read how it used to I will change it for a more specific selector like   `#canvas div[role=heading] {z-index: -1;}`

**Comment by athif23** [comment]
Okay 👍

**Comment by athif23** [comment]
Fixed as in #613
