### ISSUE TITLE
Pixels are not linted causing tests to fail on linted pull requests

### ISSUE THREAD

**Issue by TinBryn** [twilio-labs/open-pixel-art#457]
#455 Should address this, but it was detected as if I'm claiming multiple pixels, but I'm just moving other people's claims to different positions.

**Comment by sannrs** [comment]
Yeah seems like afew people didn't run npm test when submitting, I got quite confused when i submitted my pull request and saw that I failed the test saying i submitted other people's pixels.

**Comment by jesuslerma** [comment]
My PR #500 is having this issue.

**Comment by nazmanager1** [comment]
my PR #499 with similar problem

**Comment by dkundel** [comment]
I'm sorry for that inconvenience. I added a git hook to the project in #511 that will hopefully reduce this happening. At least for the people following the instructions. Maybe a GitHub Action on push would be useful that will run the linting again and will push any changes if necessary.

**Comment by jesuslerma** [comment]
Hi!, @dkundel this problem has been fixed but needs an update in CONTRIBUTING.md to remove the `npm run format:json` instruction. I will be working on that.
