### ISSUE TITLE
[TYPO] Says Pix instead of pick

### ISSUE THREAD

**Issue by ParticleMonk** [twilio-labs/open-pixel-art#4664]
## Description

In the About Project section. The current pull says, "..you can pix whatever color you prefer..." in the 4th sentence. When I believe it means to say pick.

## Expected Behavior

In the About Project section the 4th sentence should read, "...you can pick whatever color you prefer.."

## Actual Behavior

4th sentence of the About Project section reads, "...you can pix whatever color you prefer..."

## Possible Fix

Replace "x" with "ck"

## Steps to Reproduce

1. Fork the project from  github
2. Pull up the project from a local server host. 
3. Note the 4th sentence of the About Project section. 

## Context

It might just be flavor text. In which case this is a great choice! Some times these things can be dry. Maybe add a smiley face ":)" to it .

**Comment by M-S-10** [comment]
@ParticleMonk Can you assign it to me, I'll get it done ASAP!

**Comment by ranaDherya** [comment]
I have fixed this issue. Refer to pull request #4908.
@ParticleMonk
