### ISSUE TITLE
Add a unit test that verifies no username has brackets

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/open-pixel-art#49]
By default the placeholders have the format `<UNCLAIMED>`. When people claim those pixels they might be inclined to set their username as `<dkundel>` for example. It would be nice to have a unit test in `__tests__/data.js` that checks for this. Otherwise it's only being caught in CI.

This was found by @abdulajet

**Comment by zirmax** [comment]
Hey, I would like to start working on this one

**Comment by abdulajet** [comment]
sure, i’m gonna head to bed. ping if you need a hand

**Comment by ConorGrocock** [comment]
I started working on it, but forgot to comment.

**Comment by zirmax** [comment]
okay, then it's all yours @ConorGrocock  ;)

**Comment by dkundel** [comment]
Thank you everyone :)
