### ISSUE TITLE
Add test for dangerfile's allPatchesAreForTheSamePixel

### ISSUE THREAD

**Issue by KevBelisle** [twilio-labs/open-pixel-art#614]
Test is currently a placeholder:
```
describe('allPatchesAreForTheSamePixel', () => {
  test('placeholder', () => {
    expect(true).toBeTruthy();
  });
});
```

**Comment by KevBelisle** [comment]
I'll work on this one!

**Comment by KevBelisle** [comment]
The `allPatchesAreForTheSamePixel` method includes some logic to make sure the PR isn't removing or replacing a claimed pixel. It's a good check to have, but it probably shouldn't be in the `allPatchesAreForTheSamePixel` method.

**Comment by dkundel** [comment]
I'm open for some refactoring for it.

**Comment by dkundel** [comment]
@KevBelisle I'll close this issue to keep the amount of issues in check but feel free to create a PR when you refactored the function

**Comment by KevBelisle** [comment]
I probably won't have time to address this. If anyone else wants to work on it, feel free to!
