### ISSUE TITLE
Show name of contributor when hovering over pixel

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/open-pixel-art#62]
It would be cool to show the username of the person who contributed the pixel when you hover over it. Right now there's not client-side JavaScript running on the page. I won't have time to work on this myself but it would be cool to see this.

## Requirements

The page currently does not have any client-side JavaScript and even with this should stay as lightweight as possible. Please do not add a framework for this as this should be possible to be solved with vanilla JavaScript. 

The solution can be either a small popup above the canvas or a field below the canvas that gets populated with the right name when you hover/tap on a pixel. That way it would also work on mobile.

**Comment by AlexanderDavid** [comment]
I'd like to tackle this. I'm thinking that the only way to do this is to add another tag to the "rect" or "img" elements and then check the current tag under the mouse. If you think there is a better solution please lmk.
