### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by deadpyxel** [twilio-labs/open-pixel-art#704]
As someone that uses docker a lot I think it would be nice to add one or more Dockerfiles for a local `docker` setup.

That way, we would minimize the chance of conflicting versions of node and give another alternative for those that want to contribute for something more than one pixel. I am open for ideas about what kind of setup are we looking at, but if this is an approved feature, I'll get to work on this ASAP.

**Comment by dkundel** [comment]
I don't use docker too much and didn't think about it because it's a static website deployed to Netlify. I'd love to have the setup as easy as possible but if you could elaborate a bit more about the benefits and any changes it would create to the experience, I'm open for it.

**Comment by deadpyxel** [comment]
Sure thing.

## Description

The idea is that, additionally to the current setup, we would offer an option to allow the contributor to setup a docker development environment.

## Context


- One of the benefits is that the user would not have to install dependencies on their machine, having less problems with conflicting versions of node/packages and broken system configs;
- Another point is that by having that setup, the verification steps could be automated, and it would make the contribution process simpler, with less rejected PRs;
- Personally, I believe that learning how to setup a project using docker is a good thing for any developer to know, since it is currently used in many businesses;

## Possible Implementation

We could define a `Dockerfile` with something like what is shown in [Dockerizing a NodeJS application](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/):
```
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Here would come the formatting and verification steps.

EXPOSE 3000
CMD [ "npm", "start" ]
```

This is my current idea. We can adjust it for whatever are the project needs.

**Comment by dkundel** [comment]
I think that's fine. If you'd want to work on a Dockerfile and also add the part to the `CONTRIBUTING.md` on how to use it as an alternative (don't replace the basic setup) feel free to go for it

**Comment by deadpyxel** [comment]
Sure, I'll be working on this then. I just ask you to review the changes I make on the README and CONTRIBUTING.

**Comment by MatejMecka** [comment]
Hey @dkundel and @deadpyxel I submitted a Pull Request #1060 for a Docker image. If you'd like to give Feedback, suggest changes or get it merged feel free to leave a comment :D

**Comment by deadpyxel** [comment]
Congratulations on your PR, you made a better work than I was able to come up. I was forgetting about the additional files for testing.

**Comment by dkundel** [comment]
Thank you for your contribution @MatejMecka :) I'll close this one :)
