### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by deadpyxel** [twilio-labs/open-pixel-art#877]
Just recently I found out about ISSUE and PR templates.

This site can generate one with a very interesting structure:
https://www.talater.com/open-source-templates/#/

Maybe we can tailor something along those lines to help out the contribution process when it comes to feature requests and issues/bug reports.

**Comment by devgupta2607** [comment]
Can i work on this ?

**Comment by deadpyxel** [comment]
I would wait for one of the official owners of the repo to give the greenlight before starting, but I believe so.

**Comment by devgupta2607** [comment]
Ok @deadpyxel

**Comment by dkundel** [comment]
yeah I think that would be great! Right now we only have a PR template. Open for suggestions

**Comment by deadpyxel** [comment]
@devgupta2607 do you still want to take this issue?

**Comment by devgupta2607** [comment]
yes @deadpyxel

**Comment by devgupta2607** [comment]
If you want to help too @deadpyxel we can create one together

**Comment by deadpyxel** [comment]
Take a look at the new Github issue template system. Look where to put the files and look for some good templates online. I am kinda of busy this week, so I would not be of much help.

But if you have any questions, feel free to let me know.

**Comment by devgupta2607** [comment]
Ok @deadpyxel

**Comment by deadpyxel** [comment]
@devgupta2607 how are the templates going? Do you need help?

**Comment by devgupta2607** [comment]
## Description


## Expected Behavior


## Actual Behavior


## Possible Fix


## Steps to Reproduce

1.
2.
3.
4.

## Context

What else can be added?

**Comment by devgupta2607** [comment]
Another field can be added
## Issue Type
[ ] Bug Report

[ ] Feature Request

[ ] Other issue

**Comment by deadpyxel** [comment]
I know that Github issue templates allow you to specify custom templates for each type of issue (like one for bug reports, one for feature requests, etc). 

To do that you use a folder inside the `.github` called `ISSUE_TEMPLATE`, with the templates Markdown files inside. A special header let's Github determined which one it is. 

I think this would be better than using a checkbox.

**Comment by devgupta2607** [comment]
So I can create a bug report and feature request template provided by Github

**Comment by deadpyxel** [comment]
The idea is that you create de .MD files, but add then in a certain structure. Look here for a reference: https://github.com/deadpyxel/books-api/tree/master/.github
