### ISSUE TITLE
Needs Party Mode

### ISSUE THREAD

**Issue by simeydk** [twilio-labs/open-pixel-art#912]
The website has no party mode. Pixels don't ever move. This needs to be addressed.

**Comment by simeydk** [comment]
I would like to work on this.

**Comment by simeydk** [comment]
I just submitted a PR for this. You can see the deploy preview here:
https://deploy-preview-913--pixel-project-dev.netlify.com/

**Comment by dkundel** [comment]
This is absolutely amazing 😍 you are a real MVP! Thank you for this contribution!
